language: node_js
node_js:
  - "8"

env:
  global:
    - ADSERVER_URL="https://example.com"
    - DEV_XDEBUG="false"
    - APP_VERSION="travis"
    - CONTEXT_INFO="travis"

jobs:
  include:
    - if: type = pull_request
      install: true
      script: sonar-scanner

    - if: type = pull_request
      env: app_env=prod app_prod=true
      before_script:
        - envsubst < src/environments/environment.ts.template > src/environments/environment.${app_env}.ts
      script:
        - yarn build --environment ${app_env}

notifications:
  email: false
  slack:
    rooms:
      secure: "etej5c8xmeanriyve/sylffz0ft42bh1vldeliz0g7rn3lninrzh4t7i4mzhm9flbsynedrsr9rni/vk1yjlwk0g/zjfzbdslvnk3awt4zozveob33geg2b4cccel+tkqduqe5fi7pcz972lfxrop/qzg66b5gwoyvnx2siquqyb8h0xlqdbjg2tmbl7afl34nxe+ebmcex1qeq8zb/nvxkg9df/as6yhj+o+fca3savq1hnfyrvfgnhkmu8lki1xwo//y3gozryamsvcrbixpbjsm0pqptg6watayvxje9kgpwqdgqqr9fx8dyekqlaul2opm5yie/8ehxohcswftsvnrqmzrwgju3xzxqmngaxbq47nwwgy4taqdb3odzdpjfifpmsbtexamfhm7nnahe5e+q57bccwxegwmu78ucaoz/3akvqqrjfmhd91lkpatxiiz4i+s/0fdvfcmzodarueoqbzt4lizo8olosuyym3llj/ojtc9ciyyt6dpenuztmlrhce3qut5ny80j/mieqgklblnmrsuglqanz27sb1pbxs8gwn82kxms/8zqvbbdtbqgwe8qamarbeay++k+u7tp4c5cpnqzyi+qq7lv7idp0oizysmpt2xtyn//uafbrzpty1auglop/xg2ld/amgsgqibe42favalogozg="
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "iiwrvlqxomtdnsqzlguknbdgiaard0mvbjj6d8ra1jsyj9t8bgjw3egjbcawxmg5xgbqayui8upgwuadim73nlcubnz3r7ylrpu7s2j4trj2jg0pt5ymmtgaxy0ubt7a0/yxfcjlma1oq8qq3plbynqgf/oyoezzqqa2csps8vhwr7bv76crtzeq8vk/k15kulfzkuitqfpensvq7ktkpm4vkpusmzadrtz8rl+oehq8cyyfafzlwfhjg1lrlztfafcogppnu6bxsaatoqxfny+qbhrtfesyohuvj89lfhck3+8jib7loqqimp/at57j9sec3lw9bksoc1dscwhcqwlrmgb7zzn8p92km3qylaqhqf4z6q94s/u9gzwscufxg7yuvqpqkhsyewx0dx545aznmada28l+0abcbzxo35aps++jw1qltirh68vigk96x3vrpwrvcg8792bgxxipis/czjhol86tofk/cvzbgipzqt/aez5rof1sxjz8z+uzfuxirydnboqydwoaf55ajykbtjco4eb/6f/mpnybfxmhigei1k2jlq6oxtt0p9znt3cof/c6mllvc1difvposyl6td5opb4fscvdyzjnoj10bbhkkpico5sl1kcsydob9toq3qeafxh56xbbo1dxrl2czanz0pqnhhienh6zbzk="
