language: node_js
node_js:
  - '8'
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
addons:
  hosts:
    - panel.ads
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "IiwRVLQxOMtdNsqzLGUknbdgIaaRd0mVBjj6D8ra1jsYJ9T8BgjW3eGJBCAwXmG5XGBQayUi8uPgWUadIm73nlcUbnZ3R7ylRpu7s2j4tRJ2jg0PT5yMMTgAxY0UBT7A0/YxfCjLMa1oq8qq3PLbynqgF/OyOeZZqQA2Csps8VHWR7bV76CRTZEQ8VK/K15kUlfzKUitQfPenSvq7ktkpm4VKpUSmzADrTZ8RL+oEHq8cyYfAFZLwfhjg1LrLztFAFcoGPpnU6bxSaatOQxFny+QBhRTFESYoHUVJ89lFHcK3+8JiB7LoqqIMP/aT57J9SEC3lw9BKsoc1dSCwhcqwLrMgb7zZn8P92KM3qylaqhqF4z6q94s/u9gzWSCufxg7yUvQPQKHSyeWX0dX545aZnMadA28L+0aBcBZXO35aPs++jw1QLTIRh68VigK96X3VrpWrvCg8792bGXXipis/cZjHol86tOfk/cvZbgipZqt/AeZ5roF1sxJZ8z+uzFuxIRYdnBoqyDWOaf55ajYkbTJCo4eB/6F/mpNyBfXMhIgEi1k2JLQ6OxtT0p9zNT3COf/C6mllvC1DiFvPOsYL6td5Opb4FScVdYZjnOj10bBhkkpICO5sL1KCSydOb9tOq3qEAfXH56xBbo1DXrl2cZAnZ0PqNHHienH6ZBzk="
    github_token:
      secure: "Mrzs6YR8qwW/FamDoAofpWWE0ieCjOeRAOKVGCVJxpefWo3z37F2+Cxlm1HQ5hXCYsa8wh4oPJg2aJcAxvFo3j6pIgkWDjX62zAWgVUguPJtWCpPNsmGhlFPSNMZtoMQm680pmVGUU17fL9RCfav/17XcxC66VUIJv87OsBoCarx5215MX7yel2otBU5doq5O5po3/iwba9Pn2JsC2qPDD3YrRUHhN8Kl1jJSFp6V7ODrYkIiLdulz9PAhFYSp86Zz6gB2KRP1dkxy/WhdEgOA2BZgkoOmsJe3i9v91B+s0K6sqkm6ZPgo4sYNqwk6NdEmWpb7SHRCTh9QiTqVdarH+VWp3tmmRTbUmhT6390lBkbaR/PC6FLeRbO95ddTpNYPP3Fup+To9Il7pm0R/ok7pE12fgjnHXnNkdFsMXISzCjeuTKWS+DEtYao6aTwvXkIYj8ATvnQ6aWqtKMLK+0wApwyPh63eF3qZWfHG15Drz2qrfiAhaeSV/9bdy97tQhybvlPAdshWL8q4f5Vz6bDokZdq2fs/2Fr7eRDhCm91khW5gX2Ap9SJ8szRIqo1CVRNdBnzfzS8XX/dGiZPTudg/6ePElhMI9WjTUCXS0O/UingkvvJ88uYdVQhgteA8OWPo1D+CefGfa/GurXuIZCUM5U1SxaeLpeTOMRyk7Dc="
env:
  global:
    - APP_PROD="false"
    - ADSERVER_URL="http://example.com"
    - REQUEST_XDEBUG="false"

before_install:
  - envsubst < environment.ts.dist | tee src/environments/environment.dev.ts

install:
  - yarn global add @angular/cli

stages:
  - build_check
  - quality
#  - test
#  - name: deploy
#    if: branch = master

jobs:
  include:
    # node.js build
    - stage: build_check
      script: ng build --env=dev

    # Sonar Qube
    - stage: quality
      script: sonar-scanner

    # Selenium tests
#    - stage: test
#      script:
#        - mvn clean install wiremock:run &
#        - ng serve --host 0.0.0.0 --port 80 --public-host panel.ads &
#        - sleep 60
#        - mvn verify

    # Build & deploy
#    - stage: deploy
#      script: ng build --env=dev --prod
#      script: node --max_old_space_size=4096 node_modules\@angular\cli\bin\ng build --env=dev --prod

# After a build, send email push-notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure: "eTeJ5C8XmeanrIyve/sYlFFZ0fT42bH1VLDELiz0G7rn3LNinrzh4t7i4mZHm9FLBSynEdRsR9rNi/Vk1YJLWk0G/ZJFzbDSlVNk3aWT4ZOZveob33geG2b4cCCeL+TKqdUQE5Fi7PCZ972lFXRoP/qzg66b5GwoYVnx2sIquqyB8h0XlqDbjg2tMbL7AfL34nXE+EbmCex1qeq8zb/nVXKG9dF/As6yhJ+O+FcA3sAvQ1hNfyRvfGnhkmu8LkI1XWO//y3gOzRyamSvcRBIxPBJsm0PQPtG6wATAYVxjE9kGPWQDGqQR9Fx8DYeKqLAUL2OpM5yiE/8eHXohCswfTsvNrQmZrwgJU3xzXqMngaxbQ47NwwGY4TAqdB3odzDpJFIFpMSbtEXamFHM7nnAhe5E+q57bCCWxEGwmU78UcAoZ/3AKvqQRjfmHD91lKpATxiiz4i+S/0fDvfcmzOdARUeoQbzT4lIZo8oLOSuYym3lLj/Ojtc9CIYyt6DPeNuzTmLrHCE3qUT5ny80J/miEQgkLBlnMrsuglQaNz27sb1PBXS8gwn82KxmS/8zqVBbdtBQgwe8qAmArbeAY++K+u7TP4c5CpNQZyi+QQ7LV7idP0oIZYSMpt2xtyN//UAFBRZPty1augLOP/xG2lD/amgSgqibE42FaValogozg="
    on_success: change
    on_failure: always
