version: "2"

services:
  dev:
    build:
      context: .
      args:
        SYSTEM_USER_ID: 1000
        SYSTEM_USER_NAME: dev
    working_dir: /adpanel
    volumes:
    - .:/adpanel
    user: dev
    entrypoint: ['node_modules/@angular/cli/bin/ng']
    command: ['serve','--environment','dev','--host','0.0.0.0','--port','9000','--public-host','localhost']
