version: "2"

services:
  dev:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        SYSTEM_USER_ID: ${SYSTEM_USER_ID}
        SYSTEM_USER_NAME: ${SYSTEM_USER_NAME}
    working_dir: /adpanel
    volumes:
    - .:/adpanel
    user: ${SYSTEM_USER_ID}
    entrypoint: ['node_modules/@angular/cli/bin/ng']
    command: ['serve','--host','${SERVE_HOST}','--public-host','${SERVE_PUB_HOST}','--sourcemaps','--verbose']
